---
- name: Set RHVM credentials
  block:
    - ansible.builtin.set_fact:
        rhvm_uid: "{{ lookup('env','OVIRT_USERNAME') }}"
    - ansible.builtin.set_fact:
        rhvm_pwd: "{{ lookup('env','OVIRT_PASSWORD') }}"
    - ansible.builtin.set_fact:
        rhvm_url: "{{ lookup('env','OVIRT_URL') }}"

- name: Obtain SSO token
  redhat.rhv.ovirt_auth:
    url: "{{ rhvm_url }}"
    username: "{{ rhvm_uid }}"
    password: "{{ rhvm_pwd }}"
  register: auth_reg

- name: Dump auth response
  ansible.builtin.debug:
    var: auth_reg
  when: debug_mode|bool
