---
- name: Revoke SSO token
  redhat.rhv.ovirt_auth:
    state: absent
    ovirt_auth: "{{ ovirt_auth }}"
  register: revoke_auth_reg

- name: Dump revoke auth response
  ansible.builtin.debug:
    var: auth_reg
  when: debug_mode|bool
