# Check server uptime and last Ansible patching date for WebSphere servers
---
- hosts: PROD
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false
  vars:
    - was_report: '/tmp/prod_was_report.csv'

  tasks:
    - block:
        - name: Remove existing report file
          file:
            path: "{{ was_report }}"
            state: absent
          delegate_to: localhost
          run_once: true
        - name: Recreate report file
          file:
            path: "{{ was_report }}"
            state: touch
          delegate_to: localhost
          run_once: true
        - name: Add eport headers
          lineinfile:
            path: "{{ was_report }}"
            line: "Hostname,Uptime,Last Ansible Patch Date"
          delegate_to: localhost
          run_once: true
    - block:
        - name: Report uptime
          shell: /bin/uptime | awk '{print $3,$4}'
          args:
            warn: false
          register: was_uptime_reg
        - name: Run makecache first
          shell: /bin/yum makecache fast
          args:
            warn: false
        - name:
          shell: /bin/yum history | grep ansible | head -1 | awk '{print $6,$7}'
          args:
            warn: false
          register: was_patch_date_reg
        - name: Update report
          lineinfile:
            path: "{{ was_report }}"
            line: "{{ inventory_hostname }},{{ was_uptime_reg.stdout }}{{ was_patch_date_reg.stdout }}"
          delegate_to: localhost
