---
# Create a new CMDBuild server record
- import_playbook: cmdbuild_auth.yml

- hosts: all
  become: false
  gather_facts: true
  vars_files:
    - cmdbuild_vars.yml

  tasks:
    - name: Create a new machine card
      uri:
        url: "{{ cmdb_base_url }}/classes/{{ server_class }}/cards/"
        timeout: 30
        method: POST
        headers:
          Content-type: application/json
          Accept: '*/*'
          CMDBuild-Authorization: "{{ session_id }}"
        body_format: json
        body:
          Hostname: "{{ ansible_hostname }}"
          OS: "{{ ansible_distribution }}: {{ ansible_distribution_version }}"
          Host_Status: "Live"
          Provider: "{{ ansible_virtualization_type }}"
          Kernel_Version: "{{ ansible_kernel }}"
          System_UptimeV2: "{{ ( ( ansible_uptime_seconds / 60 ) / 60 ) / 24 }}"
          last_cmdb_update: "{{ ansible_date_time.date }}"
        status_code: 200
      register: create_machine_reg
    - debug:
        msg: "CMDBuild returned ID: {{ create_machine_reg.json.data._id }}"
      when: create_machine_reg.status == 20
      
