---
# Update a CMDBuild record from vars file
- import_playbook: cmdbuild_auth.yml
- import_playbook: noauth_search.yml

- hosts: all
  become: false
  vars_files:
    - cmdbuild_vars.yml
  tasks:
    - name: Append to existing comment if found
      set_fact:
        comment: "{{ get_host_by_hostname_reg.json.data[0].Comments }}\n{{ comment }}"
      when: get_host_by_hostname_reg.json.data[0].Comments
    - name: Update server record
      uri:
        url: "{{ cmdb_base_url }}/classes/{{ server_class }}/cards/{{ host_id }}"
        timeout: 30
        method: PUT
        headers:
          Content-type: application/json
          Accept: '*/*'
          CMDBuild-Authorization: "{{ session_id }}"
        body_format: json
        body:
          #Uncomment to update in CMDBuild here - refer to vars/main.yml
          #Owner: "{{ owner }}"
          #Contact: "{{ contact }}"
          #Comments: "{{ comment }}"
          #Description: "{{ description }}"
          # Set OS dynamically:
          #OS: "{{ ansible_distribution }}: {{ ansible_distribution_version }}"
          # Set OS statically:
          #OS: "{{ os }}"
          #Patching_Owner: "{{ patching_owner }}"
          #Patching_Process: "{{ patching_proc }}"
          #Support_Group: "{{ support_grp }}"
          #last_cmdb_update: "{{ ansible_date_time.date }}"
        status_code: 200
