---
# Get the default scan template for the site
- hosts: all
  become: no
  gather_facts: no
  vars_files:
    - ../vars/rapid7_vars.yml

  vars_prompt:
    - name: rapid7_user
      prompt: "Rapid7 username"
      private: no
      default: 781144

    - name: rapid7_passwd
      prompt: "Rapid7 password"
      private: yes

  tasks:
    - debug:
        msg: "Getting all scan templates"
    - name: Rapid7 API Call
      uri:
        url: "{{ rapid7_base_url }}/scan_templates"
        url_username: "{{ rapid7_user }}"
        url_password: "{{ rapid7_passwd }}"
        force_basic_auth: true
        timeout: 60
        method: GET
        headers:
          Accept: 'application/json'
        status_code: 200
      register: rapid7_scan_templates_reg
      delegate_to: localhost
    - debug:
        var: rapid7_scan_templates_reg
        
