---
# Search without auth included - assumes an existing session
# Returns a host _id value to the calling playbook
- name: "Query CMDBuild for {{ inventory_hostname }}"
  uri:
    url: "{{ cmdb_base_url }}/classes/{{ server_class }}/cards?{{ inv_filter_str }}"
    timeout: 30
    method: GET
    headers:
      Content-type: application/json
      Accept: '*/*'
      CMDBuild-Authorization: "{{ session_id }}"
    status_code: 200
  register: get_host_by_hostname_reg
- name: Parsing ID
  set_fact:
    host_id: "{{ get_host_by_hostname_reg.json.data[0]._id }}"
