---
- include_tasks: gather_host_facts.yml

- name: Ensure /etc/rsyslog.d is present
  file:
    path: /etc/rsyslog.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  ignore_errors: true

- name: Check for syslog config
  stat:
    path: /etc/rsyslog.d/00_client.conf
  register: rsyslog_conf_reg
  tags: config_check
  ignore_errors: true

- name: Add rsyslog conf file if missing
  copy:
    src: 00_client.conf
    dest: /etc/rsyslog.d/00_client.conf
    owner: root 
    mode: '0600'
  when: rsyslog_conf_reg.stat.exists|bool == false 
  notify: restart_rsyslog
  become: true
  tags: config_check
  ignore_errors: true

- name: Format message 
  set_fact:
    message: "[ { action: \"{{ logger_action }}\", message_version: \"{{ version }}\", timestamp: \"{{ ansible_date_time.iso8601 }}\", type: \"{{ ansible_os_family }}\", os: \"{{ ansible_distribution_version }}\", state: \"{{ logger_state }}\", provider: \"{{ logger_provider }}\", hostname: \"{{ ansible_hostname }}\", ip_address: \"{{ ansible_default_ipv4['address'] | default(ansible_all_ipv4_addresses[0]) }}\" } ]"
  ignore_errors: true

- name: Send message to Splunk
  shell: /usr/bin/logger -t "{{ ansible_hostname }}" "{{ message }}"
  args:
    warn: false
  ignore_errors: true
